var g;g||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,ba="undefined"!=typeof WorkerGlobalScope,ca="object"==typeof process&&process.versions?.node&&"renderer"!=process.type,da=[],ea="./this.program",fa=(a,b)=>{throw b;},ha="undefined"!=typeof document?document.currentScript?.src:void 0;"undefined"!=typeof __filename?ha=__filename:ba&&(ha=self.location.href);var ia="",ja,ka;
if(ca){var fs=require("fs");ia=__dirname+"/";ka=a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a)};ja=async a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=g);fa=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{ia=(new URL(".",ha)).href}catch{}ba&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
ja=async a=>{if(la(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}var ma=console.log.bind(console),k=console.error.bind(console),m,p=!1,na,la=a=>a.startsWith("file://"),oa,r,u,pa,qa,v,w,x,y;
function ra(a){g.onAbort?.(a);a="Aborted("+a+")";k(a);p=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var sa;async function ta(a){if(!m)try{var b=await ja(a);return new Uint8Array(b)}catch{}if(a==sa&&m)a=new Uint8Array(m);else if(ka)a=ka(a);else throw"both async and sync fetching of the wasm failed";return a}
async function ua(a,b){try{var c=await ta(a);return await WebAssembly.instantiate(c,b)}catch(d){k(`failed to asynchronously prepare wasm: ${d}`),ra(d)}}async function va(a){var b=sa;if(!m&&!la(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){k(`wasm streaming compile failed: ${d}`),k("falling back to ArrayBuffer instantiation")}return ua(b,a)}
class wa{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var xa=a=>{for(;0<a.length;)a.shift()(g)},ya=[],za=[],Aa=()=>{var a=g.preRun.shift();za.push(a)},z=0,A=null,Ba=!0,Ca="undefined"!=typeof TextDecoder?new TextDecoder:void 0,B=(a,b=0,c)=>{var d=b;for(c=d+c;a[d]&&!(d>=c);)++d;if(16<d-b&&a.buffer&&Ca)return Ca.decode(a.subarray(b,d));for(c="";b<d;){var e=a[b++];if(e&128){var h=a[b++]&63;if(192==(e&224))c+=String.fromCharCode((e&31)<<6|h);else{var f=a[b++]&63;e=224==(e&240)?(e&15)<<12|h<<6|f:(e&7)<<18|h<<12|f<<6|a[b++]&63;65536>e?c+=String.fromCharCode(e):
(e-=65536,c+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else c+=String.fromCharCode(e)}return c},Da=0,C={},Ea=a=>{a instanceof wa||"unwind"==a||fa(1,a)},Fa=a=>{na=a;Ba||0<Da||(g.onExit?.(a),p=!0);fa(a,new wa(a))},Ga=a=>{na=a;Fa(a)},Ha=()=>{if(!(Ba||0<Da))try{var a=na;na=a;Fa(a)}catch(b){Ea(b)}},Ia=a=>{if(!p)try{a(),Ha()}catch(b){Ea(b)}},Qa=(a,b)=>{Ja=a;Ka=b;if(F)if(La||=!0,0==a)G=function(){setTimeout(Ma,Math.max(0,Na+b-performance.now())|0)};else if(1==a)G=function(){Oa(Ma)};else if(2==a){if("undefined"==
typeof Pa)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Pa=d=>{c.push(d);if(ba){let e;(e=g).setImmediates??(e.setImmediates=[]);g.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}else Pa=setImmediate;G=function(){Pa(Ma)}}},Za=(a,b,c,d,e)=>{function h(){return f<Ra?(Ha(),!1):!0}F=a;Sa=d;var f=Ra;La=!1;Ma=function(){if(!p)if(0<
Ta.length){var l=Ta.shift();l.Ad(l.od);if(Ua){var n=Ua,q=0==n%1?n-1:Math.floor(n);Ua=l.rd?q:(8*n+(q+.5))/9}g.setStatus&&(l=g.statusMessage||"Please wait...",n=Ua??0,q=Va.xd??0,n?n<q?g.setStatus("{message} ({expected - remaining}/{expected})"):g.setStatus(l):g.setStatus(""));h()&&setTimeout(Ma,0)}else if(h())if(Wa=Wa+1|0,1==Ja&&1<Ka&&0!=Wa%Ka)G();else{0==Ja&&(Na=performance.now());a:if(!p){for(l of Xa)if(!1===l())break a;Ia(a);for(n of Ya)n()}h()&&G()}};e||(0<b?Qa(0,1E3/b):Qa(1,1),G());if(c)throw"unwind";
},La=!1,G=null,Ra=0,F=null,Sa=0,Ja=0,Ka=0,Wa=0,Ta=[],Xa=[],Ya=[];function $a(){G=null;Ra++}var ab=0;function Oa(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===ab)ab=b+1E3/60;else for(;b+2>=ab;)ab+=1E3/60;setTimeout(a,Math.max(ab-b,0))}}
var Va={},Na,Ma,Pa,Ua,bb=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],H=a=>{a=2<a?a?B(u,a):"":a;return bb[a]||("undefined"!=typeof document?document.querySelector(a):null)},cb=a=>0>bb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},db=[],eb,I=a=>{var b=db[a];b||(db[a]=b=eb.get(a));return b};function fb(a){var b=J.qc[a];b.target.removeEventListener(b.pc,b.Tc,b.rc);J.qc.splice(a,1)}
function gb(){if(navigator.userActivation?navigator.userActivation.isActive:J.Gc&&J.hd.Dc){var a=J.vc;J.vc=[];for(var b of a)b.Jc(...b.Pc)}}function K(a){if(!a.target)return-4;if(a.sc)a.Tc=function(c){++J.Gc;J.hd=a;gb();a.tc(c);gb();--J.Gc},a.target.addEventListener(a.pc,a.Tc,a.rc),J.qc.push(a);else for(var b=0;b<J.qc.length;++b)J.qc[b].target==a.target&&J.qc[b].pc==a.pc&&fb(b--);return 0}function hb(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var J={pd:0,Bd:0,Hc:0,Bc:0,Nc:0,Lc:0,Ec:0,vd:0,Gd:0,ud:0,Fc:0,Ic:0,Pd:0,Kc:0,Dd(a,b,c){r.set(r.subarray(b,b+c),a)},Id(){for(;J.qc.length;)fb(J.qc.length-1);J.vc=[]},Gc:0,vc:[],td(a,b,c){function d(h,f){if(h.length!=f.length)return!1;for(var l in h)if(h[l]!=f[l])return!1;return!0}for(var e of J.vc)if(e.Jc==a&&d(e.Pc,c))return;J.vc.push({Jc:a,Yc:b,Pc:c});J.vc.sort((h,f)=>h.Yc<f.Yc)},Kd(a){J.vc=J.vc.filter(b=>b.Jc!=a)},qc:[],Jd:(a,b)=>{for(var c=0;c<J.qc.length;++c)J.qc[c].target!=a||b&&b!=J.qc[c].pc||
fb(c--)},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},L=(a,b,c)=>{var d=u;if(!(0<c))return 0;var e=b;c=b+c-1;for(var h=0;h<a.length;++h){var f=a.codePointAt(h);if(127>=f){if(b>=c)break;d[b++]=f}else if(2047>=f){if(b+1>=c)break;d[b++]=192|f>>6;d[b++]=128|f&63}else if(65535>=f){if(b+2>=c)break;d[b++]=224|f>>12;d[b++]=128|f>>6&63;d[b++]=128|f&63}else{if(b+3>=c)break;d[b++]=240|f>>18;d[b++]=128|f>>12&63;d[b++]=128|f>>6&63;d[b++]=128|f&63;h++}}d[b]=0;return b-
e},ib=(a,b,c,d,e,h)=>{J.Ec||(J.Ec=M(256));a={target:H(a),pc:h,sc:d,tc:(f=event)=>{var l=f.target.id?f.target.id:"",n=J.Ec;L(hb(f.target),n+0,128);L(l,n+128,128);I(d)(e,n,b)&&f.preventDefault()},rc:c};return K(a)},jb=(a,b,c,d,e)=>{J.Fc||(J.Fc=M(276));return K({target:a,pc:e,sc:d,tc:(h=event)=>{var f=J.Fc,l=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement||document.msFullscreenElement,n=!!l;r[f]=n;r[f+1]=J.fullscreenEnabled();
var q=n?l:J.md,t=q?.id||"";L(hb(q),f+2,128);L(t,f+130,128);v[f+260>>2]=q?q.clientWidth:0;v[f+264>>2]=q?q.clientHeight:0;v[f+268>>2]=screen.width;v[f+272>>2]=screen.height;n&&(J.md=l);I(d)(19,f,b)&&h.preventDefault()},rc:c})},kb=(a,b,c,d,e,h)=>{J.Hc||(J.Hc=M(160));a={target:H(a),pc:h,sc:d,tc:f=>{var l=J.Hc;y[l>>3]=f.timeStamp;var n=l>>2;v[n+2]=f.location;r[l+12]=f.ctrlKey;r[l+13]=f.shiftKey;r[l+14]=f.altKey;r[l+15]=f.metaKey;r[l+16]=f.repeat;v[n+5]=f.charCode;v[n+6]=f.keyCode;v[n+7]=f.which;L(f.key||
"",l+32,32);L(f.code||"",l+64,32);L(f.char||"",l+96,32);L(f.locale||"",l+128,32);I(d)(e,l,b)&&f.preventDefault()},rc:c};return K(a)},lb=(a,b,c)=>{y[a>>3]=b.timeStamp;var d=a>>2;v[d+2]=b.screenX;v[d+3]=b.screenY;v[d+4]=b.clientX;v[d+5]=b.clientY;r[a+24]=b.ctrlKey;r[a+25]=b.shiftKey;r[a+26]=b.altKey;r[a+27]=b.metaKey;pa[2*d+14]=b.button;pa[2*d+15]=b.buttons;v[d+8]=b.movementX;v[d+9]=b.movementY;a=cb(c);v[d+10]=b.clientX-(a.left|0);v[d+11]=b.clientY-(a.top|0)},mb=(a,b,c,d,e,h)=>{J.Bc||(J.Bc=M(64));a=
H(a);return K({target:a,Dc:"mousemove"!=h&&"mouseenter"!=h&&"mouseleave"!=h,pc:h,sc:d,tc:(f=event)=>{lb(J.Bc,f,a);I(d)(e,J.Bc,b)&&f.preventDefault()},rc:c})},nb=(a,b,c,d)=>{J.Ic||(J.Ic=M(257));return K({target:a,pc:"pointerlockchange",sc:d,tc:(e=event)=>{var h=J.Ic,f=document.pointerLockElement;r[h]=!!f;var l=f?.id||"";L(hb(f),h+1,128);L(l,h+129,128);I(d)(20,h,b)&&e.preventDefault()},rc:c})},ob=(a,b,c,d)=>K({target:a,pc:"pointerlockerror",sc:d,tc:(e=event)=>{I(d)(38,0,b)&&e.preventDefault()},rc:c}),
pb=(a,b,c,d)=>{J.Lc||(J.Lc=M(36));a=H(a);return K({target:a,pc:"resize",sc:d,tc:(e=event)=>{if(e.target==a){var h=document.body;if(h){var f=J.Lc;v[f>>2]=0;v[f+4>>2]=h.clientWidth;v[f+8>>2]=h.clientHeight;v[f+12>>2]=innerWidth;v[f+16>>2]=innerHeight;v[f+20>>2]=outerWidth;v[f+24>>2]=outerHeight;v[f+28>>2]=pageXOffset|0;v[f+32>>2]=pageYOffset|0;I(d)(10,f,b)&&e.preventDefault()}}},rc:c})},qb=(a,b,c,d,e,h)=>{J.Kc||(J.Kc=M(1552));a=H(a);return K({target:a,Dc:"touchstart"==h||"touchend"==h,pc:h,sc:d,tc:f=>
{var l={},n=f.touches;for(var q of n)q.Uc=q.Wc=0,l[q.identifier]=q;for(var t of f.changedTouches)t.Uc=1,l[t.identifier]=t;for(var D of f.targetTouches)l[D.identifier].Wc=1;n=J.Kc;y[n>>3]=f.timeStamp;r[n+12]=f.ctrlKey;r[n+13]=f.shiftKey;r[n+14]=f.altKey;r[n+15]=f.metaKey;q=n+16;t=cb(a);D=0;for(let E of Object.values(l))if(l=q>>2,v[l]=E.identifier,v[l+1]=E.screenX,v[l+2]=E.screenY,v[l+3]=E.clientX,v[l+4]=E.clientY,v[l+5]=E.pageX,v[l+6]=E.pageY,r[q+28]=E.Uc,r[q+29]=E.Wc,v[l+8]=E.clientX-(t.left|0),v[l+
9]=E.clientY-(t.top|0),q+=48,31<++D)break;v[n+8>>2]=D;I(d)(e,n,b)&&f.preventDefault()},rc:c})},N,rb=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,h)=>b.drawArraysInstancedANGLE(c,d,e,h),a.drawElementsInstanced=(c,d,e,h,f)=>b.drawElementsInstancedANGLE(c,d,e,h,f))},sb=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),
a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},tb=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},ub=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},vb=1,O=[],P=[],wb=[],xb=[],Q=[],R=[],yb=[],zb=[],S=[],Ab={},Bb=4,Cb=0,Db=a=>{for(var b=vb++,c=a.length;c<b;c++)a[c]=null;return b},U=(a,b,c,d)=>{for(var e=0;e<a;e++){var h=N[c](),f=h&&Db(d);h?(h.name=f,d[f]=h):T||=1282;v[b+4*e>>2]=f}},Fb=(a,b)=>{a.Xc||(a.Xc=a.getContext,a.getContext=function(d,e){e=a.Xc(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.Vc?a.getContext("webgl2",b):a.getContext("webgl",b);return c?
Eb(c,b):0},Eb=(a,b)=>{var c=Db(zb),d={handle:c,attributes:b,version:b.Vc,Oc:a};a.canvas&&(a.canvas.nd=d);zb[c]=d;("undefined"==typeof b.Sc||b.Sc)&&Gb(d);return c},Gb=a=>{a||=V;if(!a.ld){a.ld=!0;var b=a.Oc;b.Fd=b.getExtension("WEBGL_multi_draw");b.zd=b.getExtension("EXT_polygon_offset_clamp");b.yd=b.getExtension("EXT_clip_control");b.Qd=b.getExtension("WEBGL_polygon_mode");rb(b);sb(b);tb(b);b.wd=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.Cd=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");
2<=a.version&&(b.Rc=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.Rc)b.Rc=b.getExtension("EXT_disjoint_timer_query");ub(b).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}},T,V,Hb=(a,b,c,d,e,h)=>{a={target:H(a),pc:h,sc:d,tc:(f=event)=>{I(d)(e,0,b)&&f.preventDefault()},rc:c};K(a)},Ib=(a,b,c,d)=>{J.Nc||(J.Nc=M(96));return K({target:a,Dc:!0,pc:"wheel",sc:d,tc:(e=event)=>{var h=J.Nc;lb(h,e,a);y[h+64>>3]=e.deltaX;y[h+72>>3]=e.deltaY;y[h+80>>3]=e.deltaZ;
v[h+88>>2]=e.deltaMode;I(d)(9,h,b)&&e.preventDefault()},rc:c})},Jb=["default","low-power","high-performance"],Kb={},Mb=()=>{if(!Lb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.language||"C").replace("-","_")+".UTF-8",_:ea||"./this.program"},b;for(b in Kb)void 0===Kb[b]?delete a[b]:a[b]=Kb[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Lb=c}return Lb},Lb,Nb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=
d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Ob=[null,[],[]],Pb=[],Qb=()=>{var a=ub(N);return a=a.concat(a.map(b=>"GL_"+b))},Rb=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=N.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>V.version){T||=1282;return}c=Qb().length;break;case 33307:case 33308:if(2>V.version){T||=1280;return}c=33307==a?3:0}if(void 0===c)switch(d=N.getParameter(a),typeof d){case "number":c=
d;break;case "boolean":c=d?1:0;break;case "string":T||=1280;return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=0;break;default:T||=1280;return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)v[b+4*a>>2]=d[a];return}try{c=
d.name|0}catch(e){T||=1280;k(`GL_INVALID_ENUM in glGet${0}v: Unknown object returned from WebGL getParameter(${a})! (error: ${e})`);return}}break;default:T||=1280;k(`GL_INVALID_ENUM in glGet${0}v: Native code calling glGet${0}v(${a}) and it returns ${d} of type ${typeof d}!`);return}v[b>>2]=c}else T||=1281},Sb=a=>{var b=Nb(a)+1,c=M(b);c&&L(a,c,b);return c},Tb=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),Ub=a=>{a-=5120;return 0==a?r:1==a?u:2==a?pa:4==a?v:6==a?x:5==a||28922==a||28520==a||30779==a||30782==
a?w:qa},W=a=>{var b=N.jd;if(b){var c=b.xc[a];"number"==typeof c&&(b.xc[a]=c=N.getUniformLocation(b,b.ed[a]+(0<c?`[${c}]`:"")));return c}T||=1282},X=[],Vb=[],Xb=a=>{var b=Nb(a)+1,c=Wb(b);L(a,c,b);return c},$b=a=>{var b=Yb();a();Zb(b)};g.requestAnimationFrame=Oa;g.pauseMainLoop=$a;g.resumeMainLoop=function(){Ra++;var a=Ja,b=Ka,c=F;F=null;Za(c,0,!1,Sa,!0);Qa(a,b);G()};g.preMainLoop&&Xa.push(g.preMainLoop);g.postMainLoop&&Ya.push(g.postMainLoop);for(let a=0;32>a;++a)Pb.push(Array(a));
for(var ac=new Float32Array(288),Y=0;288>=Y;++Y)X[Y]=ac.subarray(0,Y);var bc=new Int32Array(288);for(Y=0;288>=Y;++Y)Vb[Y]=bc.subarray(0,Y);g.noExitRuntime&&(Ba=g.noExitRuntime);g.print&&(ma=g.print);g.printErr&&(k=g.printErr);g.wasmBinary&&(m=g.wasmBinary);g.arguments&&(da=g.arguments);g.thisProgram&&(ea=g.thisProgram);if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.shift()();
var cc,dc,ec,fc,gc,hc,ic,M,Zb,Wb,Yb,jc={ia:function(){return 0},nb:()=>{},rb:function(){return 0},ja:function(){},cb:()=>ra(""),kb:()=>{Ba=!1;Da=0},lb:(a,b)=>{C[a]&&(clearTimeout(C[a].id),delete C[a]);if(!b)return 0;var c=setTimeout(()=>{delete C[a];Ia(()=>ic(a,performance.now()))},b);C[a]={id:c,Od:b};return 0},Xa:()=>{$a();F=null},K:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,Q:(a,b,c)=>{a=H(a);if(!a)return-4;a=cb(a);y[b>>3]=a.width;y[c>>3]=a.height;return 0},ba:()=>performance.now(),
Ya:()=>performance.now(),db:(a,b)=>{function c(d){I(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},_b:()=>{ra("OOM")},V:(a,b,c,d)=>ib(a,b,c,d,12,"blur"),H:(a,b,c)=>{a=H(a);if(!a)return-4;a.width=b;a.height=c;return 0},W:(a,b,c,d)=>ib(a,b,c,d,13,"focus"),U:(a,b,c,d)=>{if(!J.fullscreenEnabled())return-1;a=H(a);if(!a)return-4;jb(a,b,c,d,"webkitfullscreenchange");return jb(a,b,c,d,"fullscreenchange")},ea:(a,b,c,d)=>kb(a,b,c,d,2,"keydown"),ca:(a,b,c,d)=>kb(a,b,c,d,1,"keypress"),da:(a,
b,c,d)=>kb(a,b,c,d,3,"keyup"),eb:(a,b,c)=>{a=I(a);Za(a,b,c)},sa:(a,b,c,d)=>mb(a,b,c,d,5,"mousedown"),na:(a,b,c,d)=>mb(a,b,c,d,33,"mouseenter"),ha:(a,b,c,d)=>mb(a,b,c,d,34,"mouseleave"),oa:(a,b,c,d)=>mb(a,b,c,d,8,"mousemove"),qa:(a,b,c,d)=>mb(a,b,c,d,6,"mouseup"),Y:(a,b,c,d)=>document.body?.requestPointerLock?(a=H(a))?nb(a,b,c,d):-4:-1,X:(a,b,c,d)=>document.body?.requestPointerLock?(a=H(a))?ob(a,b,c,d):-4:-1,P:(a,b,c,d)=>pb(a,b,c,d),Z:(a,b,c,d)=>qb(a,b,c,d,25,"touchcancel"),_:(a,b,c,d)=>qb(a,b,c,d,
23,"touchend"),$:(a,b,c,d)=>qb(a,b,c,d,24,"touchmove"),aa:(a,b,c,d)=>qb(a,b,c,d,22,"touchstart"),T:(a,b,c,d)=>{Hb(a,b,c,d,31,"webglcontextlost");return 0},S:(a,b,c,d)=>{Hb(a,b,c,d,32,"webglcontextrestored");return 0},fa:(a,b,c,d)=>(a=H(a))?"undefined"!=typeof a.onwheel?Ib(a,b,c,d):-1:-4,Ea:(a,b)=>{var c=b>>2;b={alpha:!!r[b+0],depth:!!r[b+1],stencil:!!r[b+2],antialias:!!r[b+3],premultipliedAlpha:!!r[b+4],preserveDrawingBuffer:!!r[b+5],powerPreference:Jb[v[c+2]],failIfMajorPerformanceCaveat:!!r[b+12],
Vc:v[c+4],Ed:v[c+5],Sc:r[b+24],kd:r[b+25],Hd:v[c+7],Ld:r[b+32]};a=H(a);return!a||b.kd?0:Fb(a,b)},Ba:a=>{V=zb[a];g.ctx=N=V?.Oc;return!a||N?0:-5},ob:(a,b)=>{var c=0,d=0,e;for(e of Mb()){var h=b+c;w[a+d>>2]=h;c+=L(e,h,Infinity)+1;d+=4}return 0},pb:(a,b)=>{var c=Mb();w[a>>2]=c.length;a=0;for(var d of c)a+=Nb(d)+1;w[b>>2]=a;return 0},s:()=>52,mb:function(){return 52},t:()=>52,qb:function(){return 70},w:(a,b,c,d)=>{for(var e=0,h=0;h<c;h++){var f=w[b>>2],l=w[b+4>>2];b+=8;for(var n=0;n<l;n++){var q=a,t=u[f+
n],D=Ob[q];0===t||10===t?((1===q?ma:k)(B(D)),D.length=0):D.push(t)}e+=l}w[d>>2]=e;return 0},v:a=>N.activeTexture(a),p:(a,b)=>{N.attachShader(P[a],R[b])},b:(a,b)=>{35051==a?N.Qc=b:35052==a&&(N.wc=b);N.bindBuffer(a,O[b])},pa:(a,b,c)=>{N.bindBufferBase(a,b,O[c])},Zb:(a,b,c,d,e)=>{N.bindBufferRange(a,b,O[c],d,e)},f:(a,b)=>{N.bindFramebuffer(a,wb[b])},Da:(a,b)=>{N.bindRenderbuffer(a,xb[b])},u:(a,b)=>{N.bindSampler(a,S[b])},g:(a,b)=>{N.bindTexture(a,Q[b])},O:a=>{N.bindVertexArray(yb[a])},va:(a,b,c,d)=>
N.blendColor(a,b,c,d),wa:(a,b)=>N.blendEquationSeparate(a,b),x:(a,b,c,d)=>N.blendFuncSeparate(a,b,c,d),Gb:(a,b,c,d,e,h,f,l,n,q)=>N.blitFramebuffer(a,b,c,d,e,h,f,l,n,q),Oa:(a,b,c,d)=>{2<=V.version?c&&b?N.bufferData(a,u,d,c,b):N.bufferData(a,b,d):N.bufferData(a,c?u.subarray(c,c+b):b,d)},J:(a,b,c,d)=>{2<=V.version?c&&N.bufferSubData(a,b,u,d,c):N.bufferSubData(a,b,u.subarray(d,d+c))},sb:a=>N.checkFramebufferStatus(a),Aa:(a,b,c,d)=>N.clearBufferfi(a,b,c,d),z:(a,b,c)=>{N.clearBufferfv(a,b,x,c>>2)},za:(a,
b,c)=>{N.clearBufferiv(a,b,v,c>>2)},i:(a,b,c,d)=>{N.colorMask(!!a,!!b,!!c,!!d)},vb:a=>{N.compileShader(R[a])},Bb:(a,b,c,d,e,h,f,l,n)=>{2<=V.version?N.wc||!l?N.compressedTexSubImage2D(a,b,c,d,e,h,f,l,n):N.compressedTexSubImage2D(a,b,c,d,e,h,f,u,n,l):N.compressedTexSubImage2D(a,b,c,d,e,h,f,u.subarray(n,n+l))},zb:(a,b,c,d,e,h,f,l,n,q,t)=>{N.wc?N.compressedTexSubImage3D(a,b,c,d,e,h,f,l,n,q,t):N.compressedTexSubImage3D(a,b,c,d,e,h,f,l,n,u,t,q)},Ja:()=>{var a=Db(P),b=N.createProgram();b.name=a;b.Ac=b.yc=
b.zc=0;b.Mc=1;P[a]=b;return a},xb:a=>{var b=Db(R);R[b]=N.createShader(a);return b},ua:a=>N.cullFace(a),Cb:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=O[d];e&&(N.deleteBuffer(e),e.name=0,O[d]=null,d==N.Qc&&(N.Qc=0),d==N.wc&&(N.wc=0))}},q:(a,b)=>{for(var c=0;c<a;++c){var d=v[b+4*c>>2],e=wb[d];e&&(N.deleteFramebuffer(e),e.name=0,wb[d]=null)}},k:a=>{if(a){var b=P[a];b?(N.deleteProgram(b),b.name=0,P[a]=null):T||=1281}},L:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=xb[d];e&&(N.deleteRenderbuffer(e),
e.name=0,xb[d]=null)}},M:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=S[d];e&&(N.deleteSampler(e),e.name=0,S[d]=null)}},j:a=>{if(a){var b=R[a];b?(N.deleteShader(b),R[a]=null):T||=1281}},h:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=Q[d];e&&(N.deleteTexture(e),e.name=0,Q[d]=null)}},Qa:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2];N.deleteVertexArray(yb[d]);yb[d]=null}},n:a=>N.depthFunc(a),o:a=>{N.depthMask(!!a)},c:a=>N.disable(a),ra:a=>{N.disableVertexAttribArray(a)},Ib:(a,b,c)=>{N.drawArrays(a,
b,c)},Jb:(a,b,c,d)=>{N.drawArraysInstanced(a,b,c,d)},D:(a,b)=>{for(var c=Pb[a],d=0;d<a;d++)c[d]=v[b+4*d>>2];N.drawBuffers(c)},Kb:(a,b,c,d)=>{N.drawElements(a,b,c,d)},Lb:(a,b,c,d,e)=>{N.drawElementsInstanced(a,b,c,d,e)},e:a=>N.enable(a),Vb:a=>{N.enableVertexAttribArray(a)},C:(a,b,c,d)=>{N.framebufferRenderbuffer(a,b,c,xb[d])},la:(a,b,c,d,e)=>{N.framebufferTexture2D(a,b,c,Q[d],e)},tb:(a,b,c,d,e)=>{N.framebufferTextureLayer(a,b,Q[c],d,e)},ta:a=>N.frontFace(a),Pa:(a,b)=>{U(a,b,"createBuffer",O)},N:(a,
b)=>{U(a,b,"createFramebuffer",wb)},Fa:(a,b)=>{U(a,b,"createRenderbuffer",xb)},Ka:(a,b)=>{U(a,b,"createSampler",S)},Na:(a,b)=>{U(a,b,"createTexture",Q)},Sa:(a,b)=>{U(a,b,"createVertexArray",yb)},Ga:(a,b)=>N.getAttribLocation(P[a],b?B(u,b):""),a:(a,b)=>Rb(a,b),Ia:(a,b,c,d)=>{a=N.getProgramInfoLog(P[a]);null===a&&(a="(unknown error)");b=0<b&&d?L(a,d,b):0;c&&(v[c>>2]=b)},F:(a,b,c)=>{if(c)if(a>=vb)T||=1281;else if(a=P[a],35716==b)a=N.getProgramInfoLog(a),null===a&&(a="(unknown error)"),v[c>>2]=a.length+
1;else if(35719==b){if(!a.Ac){var d=N.getProgramParameter(a,35718);for(b=0;b<d;++b)a.Ac=Math.max(a.Ac,N.getActiveUniform(a,b).name.length+1)}v[c>>2]=a.Ac}else if(35722==b){if(!a.yc)for(d=N.getProgramParameter(a,35721),b=0;b<d;++b)a.yc=Math.max(a.yc,N.getActiveAttrib(a,b).name.length+1);v[c>>2]=a.yc}else if(35381==b){if(!a.zc)for(d=N.getProgramParameter(a,35382),b=0;b<d;++b)a.zc=Math.max(a.zc,N.getActiveUniformBlockName(a,b).length+1);v[c>>2]=a.zc}else v[c>>2]=N.getProgramParameter(a,b);else T||=1281},
ub:(a,b,c,d)=>{a=N.getShaderInfoLog(R[a]);null===a&&(a="(unknown error)");b=0<b&&d?L(a,d,b):0;c&&(v[c>>2]=b)},ma:(a,b,c)=>{c?35716==b?(a=N.getShaderInfoLog(R[a]),null===a&&(a="(unknown error)"),v[c>>2]=a?a.length+1:0):35720==b?(a=N.getShaderSource(R[a]),v[c>>2]=a?a.length+1:0):v[c>>2]=N.getShaderParameter(R[a],b):T||=1281},Ta:(a,b)=>{if(2>V.version)return T||=1282,0;var c=Ab[a];if(c)return 0>b||b>=c.length?(T||=1281,0):c[b];switch(a){case 7939:return c=Qb().map(Sb),c=Ab[a]=c,0>b||b>=c.length?(T||=
1281,0):c[b];default:return T||=1280,0}},E:(a,b)=>{b=b?B(u,b):"";if(a=P[a]){var c=a,d=c.xc,e=c.gd,h;if(!d){c.xc=d={};c.ed={};var f=N.getProgramParameter(c,35718);for(h=0;h<f;++h){var l=N.getActiveUniform(c,h);var n=l.name;l=l.size;var q=Tb(n);q=0<q?n.slice(0,q):n;var t=c.Mc;c.Mc+=l;e[q]=[l,t];for(n=0;n<l;++n)d[t]=n,c.ed[t++]=q}}c=a.xc;d=0;e=b;h=Tb(b);0<h&&(d=parseInt(b.slice(h+1))>>>0,e=b.slice(0,h));if((e=a.gd[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||N.getUniformLocation(a,b)))return d}else T||=1281;return-1},
Fb:(a,b,c)=>{for(var d=Pb[b],e=0;e<b;e++)d[e]=v[c+4*e>>2];N.invalidateFramebuffer(a,d)},G:a=>{a=P[a];N.linkProgram(a);a.xc=0;a.gd={}},Ra:(a,b)=>{3317==a?Bb=b:3314==a&&(Cb=b);N.pixelStorei(a,b)},y:(a,b)=>N.polygonOffset(a,b),Hb:a=>N.readBuffer(a),Ca:(a,b,c,d,e)=>N.renderbufferStorageMultisample(a,b,c,d,e),I:(a,b,c)=>{N.samplerParameterf(S[a],b,c)},d:(a,b,c)=>{N.samplerParameteri(S[a],b,c)},A:(a,b,c,d)=>N.scissor(a,b,c,d),wb:(a,b,c,d)=>{for(var e="",h=0;h<b;++h){var f=(f=w[c+4*h>>2])?B(u,f,d?w[d+4*
h>>2]:void 0):"";e+=f}N.shaderSource(R[a],e)},Eb:(a,b,c)=>N.stencilFunc(a,b,c),ya:(a,b,c,d)=>N.stencilFuncSeparate(a,b,c,d),m:a=>N.stencilMask(a),Db:(a,b,c)=>N.stencilOp(a,b,c),xa:(a,b,c,d)=>N.stencilOpSeparate(a,b,c,d),Ma:(a,b,c,d,e)=>N.texStorage2D(a,b,c,d,e),La:(a,b,c,d,e,h)=>N.texStorage3D(a,b,c,d,e,h),Ab:(a,b,c,d,e,h,f,l,n)=>{if(2<=V.version){if(N.wc){N.texSubImage2D(a,b,c,d,e,h,f,l,n);return}if(n){var q=Ub(l);N.texSubImage2D(a,b,c,d,e,h,f,l,q,n>>>31-Math.clz32(q.BYTES_PER_ELEMENT));return}}if(n){q=
Ub(l);var t=h*((Cb||e)*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[f-6402]||1)*q.BYTES_PER_ELEMENT+Bb-1&-Bb);n=q.subarray(n>>>31-Math.clz32(q.BYTES_PER_ELEMENT),n+t>>>31-Math.clz32(q.BYTES_PER_ELEMENT))}else n=null;N.texSubImage2D(a,b,c,d,e,h,f,l,n)},yb:(a,b,c,d,e,h,f,l,n,q,t)=>{if(N.wc)N.texSubImage3D(a,b,c,d,e,h,f,l,n,q,t);else if(t){var D=Ub(q);N.texSubImage3D(a,b,c,d,e,h,f,l,n,q,D,t>>>31-Math.clz32(D.BYTES_PER_ELEMENT))}else N.texSubImage3D(a,b,c,d,e,h,f,l,n,q,null)},Ub:(a,
b,c)=>{if(2<=V.version)b&&N.uniform1fv(W(a),x,c>>2,b);else{if(288>=b)for(var d=X[b],e=0;e<b;++e)d[e]=x[c+4*e>>2];else d=x.subarray(c>>2,c+4*b>>2);N.uniform1fv(W(a),d)}},Ha:(a,b)=>{N.uniform1i(W(a),b)},Qb:(a,b,c)=>{if(2<=V.version)b&&N.uniform1iv(W(a),v,c>>2,b);else{if(288>=b)for(var d=Vb[b],e=0;e<b;++e)d[e]=v[c+4*e>>2];else d=v.subarray(c>>2,c+4*b>>2);N.uniform1iv(W(a),d)}},Tb:(a,b,c)=>{if(2<=V.version)b&&N.uniform2fv(W(a),x,c>>2,2*b);else{if(144>=b){b*=2;for(var d=X[b],e=0;e<b;e+=2)d[e]=x[c+4*e>>
2],d[e+1]=x[c+(4*e+4)>>2]}else d=x.subarray(c>>2,c+8*b>>2);N.uniform2fv(W(a),d)}},Pb:(a,b,c)=>{if(2<=V.version)b&&N.uniform2iv(W(a),v,c>>2,2*b);else{if(144>=b){b*=2;for(var d=Vb[b],e=0;e<b;e+=2)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2]}else d=v.subarray(c>>2,c+8*b>>2);N.uniform2iv(W(a),d)}},Sb:(a,b,c)=>{if(2<=V.version)b&&N.uniform3fv(W(a),x,c>>2,3*b);else{if(96>=b){b*=3;for(var d=X[b],e=0;e<b;e+=3)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2],d[e+2]=x[c+(4*e+8)>>2]}else d=x.subarray(c>>2,c+12*b>>2);N.uniform3fv(W(a),
d)}},Ob:(a,b,c)=>{if(2<=V.version)b&&N.uniform3iv(W(a),v,c>>2,3*b);else{if(96>=b){b*=3;for(var d=Vb[b],e=0;e<b;e+=3)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2],d[e+2]=v[c+(4*e+8)>>2]}else d=v.subarray(c>>2,c+12*b>>2);N.uniform3iv(W(a),d)}},Rb:(a,b,c)=>{if(2<=V.version)b&&N.uniform4fv(W(a),x,c>>2,4*b);else{if(72>=b){var d=X[4*b],e=x;c>>=2;b*=4;for(var h=0;h<b;h+=4){var f=c+h;d[h]=e[f];d[h+1]=e[f+1];d[h+2]=e[f+2];d[h+3]=e[f+3]}}else d=x.subarray(c>>2,c+16*b>>2);N.uniform4fv(W(a),d)}},Nb:(a,b,c)=>{if(2<=
V.version)b&&N.uniform4iv(W(a),v,c>>2,4*b);else{if(72>=b){b*=4;for(var d=Vb[b],e=0;e<b;e+=4)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2],d[e+2]=v[c+(4*e+8)>>2],d[e+3]=v[c+(4*e+12)>>2]}else d=v.subarray(c>>2,c+16*b>>2);N.uniform4iv(W(a),d)}},Mb:(a,b,c,d)=>{if(2<=V.version)b&&N.uniformMatrix4fv(W(a),!!c,x,d>>2,16*b);else{if(18>=b){var e=X[16*b],h=x;d>>=2;b*=16;for(var f=0;f<b;f+=16){var l=d+f;e[f]=h[l];e[f+1]=h[l+1];e[f+2]=h[l+2];e[f+3]=h[l+3];e[f+4]=h[l+4];e[f+5]=h[l+5];e[f+6]=h[l+6];e[f+7]=h[l+7];e[f+
8]=h[l+8];e[f+9]=h[l+9];e[f+10]=h[l+10];e[f+11]=h[l+11];e[f+12]=h[l+12];e[f+13]=h[l+13];e[f+14]=h[l+14];e[f+15]=h[l+15]}}else e=x.subarray(d>>2,d+64*b>>2);N.uniformMatrix4fv(W(a),!!c,e)}},l:a=>{a=P[a];N.useProgram(a);N.jd=a},Wb:(a,b)=>{N.vertexAttribDivisor(a,b)},Xb:(a,b,c,d,e)=>{N.vertexAttribIPointer(a,b,c,d,e)},Yb:(a,b,c,d,e,h)=>{N.vertexAttribPointer(a,b,c,!!d,e,h)},B:(a,b,c,d)=>N.viewport(a,b,c,d),jb:Fa,ib:function(){g.Zc=a=>{0!=ec()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",
g.Zc)},gb:function(){g.dd=a=>{const b=a.clipboardData.getData("text");$b(()=>{const c=Xb(b);dc(c)})};window.addEventListener("paste",g.dd)},fb:function(){g.Md=[];g.$c=b=>{b.stopPropagation();b.preventDefault()};g.ad=b=>{b.stopPropagation();b.preventDefault()};g.bd=b=>{b.stopPropagation();b.preventDefault()};g.cd=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;g.Nd=c;fc(c.length);for(let e=0;e<c.length;e++)$b(()=>{const h=Xb(c[e].name);gc(e,h)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&
(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);hc(b.clientX,b.clientY,d)};const a=g.uc;a.addEventListener("dragenter",g.$c,!1);a.addEventListener("dragleave",g.ad,!1);a.addEventListener("dragover",g.bd,!1);a.addEventListener("drop",g.cd,!1)},_a:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},ab:function(a){g.Cc&&(URL.revokeObjectURL(g.Cc[a].qd),g.Cc[a]=null)},bb:function(){document.exitPointerLock&&document.exitPointerLock()},hb:function(a,b){0!==b&&(document.title=
b?B(u,b):"");a=a?B(u,a):"";void 0!==g.canvas&&("object"===typeof g.canvas?bb[a]=g.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));g.uc=H(a);g.uc||console.warn("sokol_app.h: can't find html5_canvas_selector ",a);g.uc.requestPointerLock||console.warn("sokol_app.h: target doesn't support requestPointerLock: ",a)},Wa:function(){window.removeEventListener("beforeunload",g.Zc)},Va:function(){window.removeEventListener("paste",g.dd)},Ua:function(){const a=g.uc;a.removeEventListener("dragenter",
g.$c);a.removeEventListener("dragleave",g.ad);a.removeEventListener("dragover",g.bd);a.removeEventListener("drop",g.cd)},r:function(){g.uc&&g.uc.requestPointerLock&&g.uc.requestPointerLock()},R:function(a,b,c){if(g.uc){if(0===b)a="none";else if(0!=c)a=g.Cc[a].sd;else switch(a){case 0:a="auto";break;case 1:a="default";break;case 2:a="text";break;case 3:a="crosshair";break;case 4:a="pointer";break;case 5:a="ew-resize";break;case 6:a="ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";
break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;default:a="auto"}g.uc.style.cursor=a}},Za:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const e=d.getContext("2d"),h=e.createImageData(a,b);h.data.set(u.subarray(c,c+a*b*4));e.putImageData(h,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},$a:function(a){a=a?B(u,a):"";const b=document.createElement("textarea");b.setAttribute("autocomplete",
"off");b.setAttribute("autocorrect","off");b.setAttribute("autocapitalize","off");b.setAttribute("spellcheck","false");b.style.left="-100px";b.style.top="-100px";b.style.height=1;b.style.width=1;b.value=a;document.body.appendChild(b);b.select();document.execCommand("copy");document.body.removeChild(b)},ka:function(){return navigator.userAgent.includes("Macintosh")?1:0},ga:function(a,b){b=b?B(u,b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;
default:console.info(b)}}};function kc(a=[]){var b=cc;a.unshift(ea);var c=a.length,d=Wb(4*(c+1)),e=d;a.forEach(f=>{w[e>>2]=Xb(f);e+=4});w[e>>2]=0;try{var h=b(c,d);Ga(h)}catch(f){Ea(f)}}
function lc(a=da){function b(){g.calledRun=!0;if(!p){Z.ac();g.onRuntimeInitialized?.();g.noInitialRun||kc(a);if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var c=g.postRun.shift();ya.push(c)}xa(ya)}}if(0<z)A=lc;else{if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)Aa();xa(za);0<z?A=lc:g.setStatus?(g.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>g.setStatus(""),1);b()},1)):b()}}var Z;
(async function(){function a(c){Z=c.exports;oa=Z.$b;c=oa.buffer;r=new Int8Array(c);pa=new Int16Array(c);u=new Uint8Array(c);qa=new Uint16Array(c);v=new Int32Array(c);w=new Uint32Array(c);x=new Float32Array(c);y=new Float64Array(c);new BigInt64Array(c);new BigUint64Array(c);eb=Z.oc;c=Z;g._main=cc=c.bc;g.__sapp_emsc_onpaste=dc=c.cc;g.__sapp_html5_get_ask_leave_site=ec=c.dc;g.__sapp_emsc_begin_drop=fc=c.ec;g.__sapp_emsc_drop=gc=c.fc;g.__sapp_emsc_end_drop=hc=c.gc;g.__sapp_emsc_invoke_fetch_cb=c.hc;g.__sapp_emsc_set_fullscreen_flag=
c.ic;ic=c.jc;M=c.kc;Zb=c.lc;Wb=c.mc;Yb=c.nc;z--;g.monitorRunDependencies?.(z);0==z&&A&&(c=A,A=null,c());return Z}z++;g.monitorRunDependencies?.(z);var b={a:jc};if(g.instantiateWasm)return new Promise(c=>{g.instantiateWasm(b,(d,e)=>{c(a(d,e))})});sa??=g.locateFile?g.locateFile("voxels.wasm",ia):ia+"voxels.wasm";return a((await va(b)).instance)})();lc();
